image: tmaier/docker-compose:latest

stages:
  - build_production
  - deploy_production
  - build_dev
  - deploy_dev

variables:
  KUBECONFIG: /etc/deploy/config


build_production:
  stage: build_production
  image: docker:17.09.0-ce

  services:
    - docker:17.09.0-ce-dind

  script:
    - apk add --no-cache curl jq python py-pip
    - echo $prod_posxdata_json | base64 -d > ${HOME}/gcloud-gcr-key.json
    - cat ${HOME}/gcloud-gcr-key.json | docker login -u _json_key --password-stdin https://gcr.io
    - docker build -f Dockerfile -t gcr.io/posxdata/hikeup:production-${CI_PIPELINE_ID} .
    - docker push gcr.io/posxdata/hikeup:production-${CI_PIPELINE_ID}
  only:
    - master

deploy_production:
  variables:
    GIT_STRATEGY: none

  stage: deploy_production

  image: shoppinpal/git-ssh

  script:
    - git config --global user.email "devops@shoppinpal.com"
    - git config --global user.name "Gitlab CI"
    - mkdir -p ~/.ssh
    - mkdir -p /tmp/kubernetes
    - echo $POSXDATA_KUBERNETES_KEY | base64 -d > ~/.ssh/ssh_key
    - echo $GITLAB_SSH_KNOWN_HOSTS_LINE | base64 -d > ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/ssh_key
    - >
      echo "
      Host gitlab.shoppinpal.com
        IdentityFile ~/.ssh/ssh_key
      " > ~/.ssh/config
    - git clone git@gitlab.shoppinpal.com:devops/posxdata-kubernetes.git /tmp/kubernetes
    - cd /tmp/kubernetes
    - /tmp/kubernetes/hikeup_generate.sh production-${CI_PIPELINE_ID}
    - git commit -a -m "Deploy hikeup version production-${CI_PIPELINE_ID}"
    - git push

  only:
    - master

build_dev:
    stage: build_dev
    image: docker:17.09.0-ce

    services:
        - docker:17.09.0-ce-dind
    when: manual
    allow_failure: false

    script:
        - apk add --no-cache curl jq python py-pip
        - echo $dev_posxdata_json | base64 -d > ${HOME}/gcloud-gcr-key.json
        - cat ${HOME}/gcloud-gcr-key.json | docker login -u _json_key --password-stdin https://gcr.io
        - docker build -f Dockerfile -t gcr.io/dev-posxdata/hikeup:dev-${CI_PIPELINE_ID} .
        - docker push gcr.io/dev-posxdata/hikeup:dev-${CI_PIPELINE_ID}

    except:
        - master

deploy_dev:
  variables:
    GIT_STRATEGY: none

  stage: deploy_dev

  image: shoppinpal/git-ssh
  dependencies:
  - build_dev
  needs:
  - build_dev

  script:
    - git config --global user.email "devops@shoppinpal.com"
    - git config --global user.name "Gitlab CI"
    - mkdir -p ~/.ssh
    - mkdir -p /tmp/kubernetes
    - echo $DEV_POSXDATA_KUBERNETES_KEY | base64 -d > ~/.ssh/ssh_key
    - echo $DEV_GITLAB_SSH_KNOWN_HOSTS_LINE | base64 -d > ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/ssh_key
    - >
      echo "
      Host gitlab.shoppinpal.com
        IdentityFile ~/.ssh/ssh_key
      " > ~/.ssh/config
    - git clone git@gitlab.shoppinpal.com:devops/dev-posxdata-kubernetes.git /tmp/kubernetes
    - cd /tmp/kubernetes
    - /tmp/kubernetes/hikeup_generate.sh dev-${CI_PIPELINE_ID}
    - git commit -a -m "Deploy hikeup version dev-${CI_PIPELINE_ID}"
    - git push

  except:
    - master
